spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IssamLaoumri/supshare-config-repo.git
          clone-on-start: true
          default-label: main
  application:
    name: config-service

server:
  port: 9297